# Generated by Django 5.2.1 on 2025-06-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_usersignup_profile_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignup',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
